services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - chris_network
    image: nginx # give name of image
    ports:
      - "443:443"
    volumes:
      - dehvidpress:/home/www
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - chris_network
    image: mariadb
    volumes:
      - florian_db:/database
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - chris_network
    image: wordpress
    volumes:
      - dehvidpress:/website

networks:
  chris_network:

volumes:
  florian_db:
      driver_opts:
        type: none
        o: bind
        device: /home/tlassere/data/mariadb/
  dehvidpress:
      driver_opts:
        type: none
        o: bind
        device: /home/tlassere/data/website/
