services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - chris_network
    image: nginx # give name of image
    ports:
      - "443:443"

networks:
  chris_network: