services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - chris_network
    image: nginx # give name of image
    ports:
      - "443:443"
    volumes:
      - dehvidpress:/home/www
    restart: unless-stopped
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - chris_network
    image: mariadb
    volumes:
      - florian_db:/database
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_PASS_R=${MYSQL_PASS_R}
      - MYSQL_NAME=${MYSQL_NAME}
    restart: unless-stopped
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - chris_network
    image: wordpress
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASS=${WORDPRESS_ADMIN_PASS}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_NAME=${MYSQL_NAME}
    volumes:
      - dehvidpress:/home/www
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    networks:
      - chris_network
    restart: unless-stopped
    volumes:
      - dehvidpress:/home/www
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    networks:
      - chris_network
    image: ftp
    restart: unless-stopped
    volumes:
      - dehvidpress:/home/www
    ports:
      - "20:20"

networks:
  chris_network:

volumes:
  florian_db:
      driver_opts:
        type: none
        o: bind
        device: /home/tlassere/data/mariadb/
  dehvidpress:
      driver_opts:
        type: none
        o: bind
        device: /home/tlassere/data/website/
