FROM alpine:3.19.2

RUN apk add vim
RUN apk add php82
RUN apk add php82-phar
RUN apk add php82-fpm
RUN apk add php82-iconv

# se module permet de communiquer entre le php et la base de donner
RUN apk add php82-mysqli

RUN mkdir -p /home/www
RUN mkdir -p wordpress_file

RUN rm /etc/php82/php-fpm.d/www.conf

RUN adduser --disabled-password wordpress_user
RUN adduser --disabled-password nginx

RUN chown wordpress_user:wordpress_user /home/www

COPY [ "./tools", "tools" ]
RUN [ "chmod", "+x", "./tools/script.sh" ]

COPY ./conf/php_wordpress.conf /etc/php82/php-fpm.d/php_wordpress.conf

RUN chown wordpress_user:wordpress_user /var/log/php82/
RUN chown wordpress_user:wordpress_user wordpress_file

#USER wordpress_user

ENTRYPOINT [ "./tools/script.sh", "php-fpm82", "-F" ]

EXPOSE 9000/tcp
